### ISSUE TITLE
HowTo for Update

### ISSUE THREAD

**Issue by apachler** [josepsanzcamp/SaltOS#2]
There is no description available how i can Update my r6600 to a newer version like r7680 or something.

**Comment by josepsanzcamp** [comment]
Hi Andreas.

I'm planning to do a post in our blog at http://blog.saltos.org/ for explain how to do an upgrade succesfully without losing data. Follow our RSS at http://www.saltos.org/portal/en/xml/rss.xml to be informed about all our news.

Thanks.
