### ISSUE TITLE
Application names not translateable

### ISSUE THREAD

**Issue by apachler** [josepsanzcamp/SaltOS#3]
I can not find any way to translate the application names, it seems that the names are static defined in database table "tbl_aplicaciones"
![applications](https://cloud.githubusercontent.com/assets/3908272/9957886/64f9a530-5e04-11e5-8ba3-0c05d3b4e466.jpg)

**Comment by josepsanzcamp** [comment]
Hi Andreas.

You can solve the issue translating the nodes <nombre> of the xml/dbstatic.xml file. I'm planning a fix for this issue, but I have a lot of work!!!.

Thanks.
