### ISSUE TITLE
Captcha does not work at main website

### ISSUE THREAD

**Issue by hamzamu** [josepsanzcamp/SaltOS#5]
Hello,  This issue is not related to SaltOS, but it's about http://www.saltos.org/portal/en/home .

The Captcha does not work at the main website, in the contact form, and in the demo submit form as well.

**Comment by josepsanzcamp** [comment]
Hi Hamza Mousa.

Thanks by your notification.

Effectively the web site that uses rhinos seems to live a problems with the automatic cache generation and the concurrence (I think!!!).

I'm doing changes to fix it, but the main problem is that I don't know how to reproduce the error. I think that I must to wait to check if the error returns to appear or not.

If you experience the same problem, please, be free to add a comment in this issue.

Josep.

**Comment by josepsanzcamp** [comment]
Hi Hamza Mousa.

Seems that the bug was fixed.

I close the issue.

Thanks by your notice.

Josep.

**Comment by josepsanzcamp** [comment]
Hi another time.

The real bug was detected and fixed some days ago and only affects to the rhinos code.

Thanks by your notice.

Josep.
