### ISSUE TITLE
Can I install it on LAMP or Wamp?

### ISSUE THREAD

**Issue by ugintl** [josepsanzcamp/SaltOS#6]
Does it only work on centos?

**Comment by josepsanzcamp** [comment]
No, SaltOS can work in all servers with PHP and MySQL/MariaDB/SQLite.

The optimal configuration is to run SaltOS under GNU/Linux that is the environment more tested, but on Windows severs too must to work.

Currently I'm using debian to work and devel, but all distros are good for SaltOS.

Josep.

**Comment by ugintl** [comment]
@josepsanzcamp I just noticed that it says "SaltOS is a cloud computing management solution". Is it specifically built for this purpose? I was looking for a general CRM/ERP.

**Comment by josepsanzcamp** [comment]
Yes, it's build to be used using a browser, without installing nothing in the client side!!!
