### ISSUE TITLE
Error al generar facturas periódicas.

### ISSUE THREAD

**Issue by Xrizoo** [josepsanzcamp/SaltOS#7]
Hola Josep,
En la demo que tienes activa, he estado probando el tema de la facturas períodicas, y cuando he ido a genera me aparece lo siguiente: 
`
SaltOS v3.7 r9982
DB Error

SQLSTATE[HY000]: General error: 1 table tbl_facturas has no column named meses

Query

INSERT INTO tbl_facturas(id_cliente,id_epigrafe,nombre,direccion,id_pais,id_provincia,id_poblacion,id_codpostal,nombre_pais,nombre_provincia,nombre_poblacion,nombre_codpostal,cif,fecha,iva,irpf,id_cuenta,fecha2,id_periodica,meses,id_formapago) SELECT '101','1',nombre,direccion,id_pais,id_provincia,id_poblacion,id_codpostal,nombre_pais,nombre_provincia,nombre_poblacion,nombre_codpostal,cif,'2023-05-01','0','0','1','2023-05-01','2','1','6' FROM tbl_clientes WHERE id=101

Backtrace

0 => show_php_error (in file pdo_sqlite.php:144)
1 => db_query (in class database_pdo_sqlite) (in file database.php:59)
2 => db_query (in file liquidar.php:481)
3 => require (in file default.php:33)
4 => require (in file index.php:85)

Debug

user => demo
page => periodicas
action => liquidar
id => 2

`
Un saludo!!!.

**Comment by josepsanzcamp** [comment]
Buenos dias @Xrizoo 

Ya he arreglado el bug, se trataba de un error en el nombre del campo, en lugar de ser meses debía ser mes_periodica, ya esta aplicado el cambio en el entorno de test y demos, esta noche se publicará el cambio en github con el r9983.

Gracias por notificar el problema.

Josep.

**Comment by Xrizoo** [comment]
Gracias a ti Josep.
Tu soft es una joya.
1 saludo.

**Comment by josepsanzcamp** [comment]
Como extra, y dado que el campo mes es obligatorio para poder generar las facturas periódicas, he añadido el filtro del campo mes en la pantalla principal para facilitar su uso, ya esta aplicado el cambio en el entorno de test y demos, esta noche se publicará el cambio en github con el r9984.

**Comment by Xrizoo** [comment]
Genial! Lo pruebo en cuanto lo vea actualizado y te cuento.
Mas que gracias!!!

**Comment by Xrizoo** [comment]
Funciona perfectamente!
Muy muchas gracias Josep.
